filebeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true
      hints.default_config.enabled: false

filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

filebeat.modules:
  - module: elasticsearch
  - module: logstash

setup.template.settings:
  index.number_of_shards: 1

setup.kibana:
  host: "kibana:5601"

output.elasticsearch:
  enabled: false
  hosts: ["elasticsearch:9200"]
  index: "filebeats-%{[@metadata][beat]}-%{+YYYY.MM.dd}"

output.logstash:
  enabled: true
  hosts: ["logstash:5044"]

processors:
  - drop_fields:
      fields: ["agent.ephemeral_id", "agent.hostname", "agent.id", "agent.name", "agent.version", "docker.container.labels.com_docker_compose_version", "ecs.version", "host.name", "input.type", "kubernetes.container.image", "log.offset", "docker.container.labels.com_docker_compose_project_working_dir", "log.file.path" ]
      ignore_missing: false

monitoring.enabled: false
logging.metrics.enabled: false
logging.level: debug
logging.selectors: ["*"]
logging.to_files: true
# logging.files:
#   path: /var/log/filebeat
#   name: filebeat.log
#   keepfiles: 7
#   permissions: 0644