- pipeline.id: main
  # pipeline.workers: 1
  # pipeline.batch.size: 1
  path.config: "/usr/share/logstash/pipeline/logstash.conf"

# - pipeline.id: p2p_api
#   path.config: "/usr/share/logstash/pipeline/p2p_api_pipeline.conf"