- pipeline.id: main
  # pipeline.workers: 1
  # pipeline.batch.size: 1
  path.config: "/usr/share/logstash/pipeline/logstash.conf"

# - pipeline.id: p2p_api
#   path.config: "/usr/share/logstash/pipeline/p2p_api_pipeline.conf" # "../../*.conf"

- pipeline.id: from-scratch-pipeline
  path.config: "/usr/share/logstash/pipeline/from-scratch.conf"

- pipeline.id: incremental-pipeline
  path.config: "/usr/share/logstash/pipeline/incremental.conf"